// Phase 9C: Astro exporter.
//
// Astro pages are HTML supersets of static HTML, so the site that
// buildMultiPageExport already produces maps almost 1:1: each exported
// page becomes `src/pages/<slug>.astro` (full HTML document — Astro only
// requires a default export for components, pages may be raw HTML), the
// shared stylesheet and extracted JS files move to `public/`, and inline
// runtime scripts are marked `is:inline` so Astro's bundler leaves them
// verbatim. Result: `npx astro build` emits a static site with the exact
// same DOM and cascade as the plain HTML zip.
import { buildMultiPageExport } from "../exportHtml";

const pkgName = (name) =>
  (String(name || "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "web-dojo-site");

// Astro treats <script> as a module to bundle unless marked is:inline; the
// exported HTML's scripts are plain, self-contained runtime snippets
// (widget fetches, the on-scroll/click animation bootstraps, custom JS).
const markInlineScripts = (html) => html.replace(/<script>/g, "<script is:inline>");

// The HTML build emits root-relative-to-page asset refs; under Astro the
// shared assets live in public/, which Astro serves from the site root.
const rewriteAssetPaths = (html) =>
  html.replace(/href="globals\.css"/g, 'href="/globals.css"').replace(/src="js\//g, 'src="/js/');

export const buildAstroExport = (project) => {
  const { files: htmlFiles } = buildMultiPageExport(project);
  const files = {};

  Object.entries(htmlFiles).forEach(([name, content]) => {
    if (!name.endsWith(".html")) {
      // globals.css, js/*.js, imgs/.keep, fonts/.keep → public/
      files[`public/${name}`] = content;
      return;
    }
    const slug = name.slice(0, -5);
    const page = (project.pages || []).find((p) => (p.slug || "index") === slug);
    const bodyMatch = content.match(/<body([^>]*)>([\s\S]*)<\/body>/i);
    const headMatch = content.match(/<head>([\s\S]*)<\/head>/i);
    const bodyAttrs = bodyMatch ? bodyMatch[1] : "";
    const head = rewriteAssetPaths(markInlineScripts(headMatch ? headMatch[1] : ""));
    const body = rewriteAssetPaths(markInlineScripts(bodyMatch ? bodyMatch[2] : ""));
    files[`src/pages/${slug === "index" ? "index" : slug}.astro`] = `---
// Web Dojo export — page "${(page && page.name) || project.name || "Untitled"}" (route /${slug === "index" ? "" : slug})
---
<!doctype html>
<html lang="en">
<head>${head}</head>
<body${bodyAttrs}>
${body}
</body>
</html>
`;
  });

  files["package.json"] = `${JSON.stringify(
    {
      name: pkgName(project.name),
      type: "module",
      version: "1.0.0",
      private: true,
      scripts: { dev: "astro dev", build: "astro build", preview: "astro preview" },
      dependencies: { astro: "^4.16.18" },
    },
    null,
    2
  )}\n`;

  files["astro.config.mjs"] = `import { defineConfig } from "astro/config";

// Static output: "npm run build" produces ./dist ready for FTP upload —
// the same deployment shape as Web Dojo's plain HTML export.
export default defineConfig({});
`;

  files["tsconfig.json"] = `${JSON.stringify({ extends: "astro/tsconfigs/base" }, null, 2)}\n`;

  files[".gitignore"] = "node_modules/\ndist/\n.astro/\n";

  files["README.md"] = `# ${project.name || "Web Dojo site"} (Astro)

Generated by Web Dojo's Astro exporter. Pages live in \`src/pages/\`, the
shared stylesheet and runtime scripts in \`public/\`.

    npm install
    npm run dev      # http://localhost:4321
    npm run build    # static site in ./dist — upload with FTP/SFTP as usual
`;

  return { files };
};
