// Curated list of Monaco built-in languages that cover the popular web
// frameworks & full-stack development stacks. Monaco ships grammars for all
// of these — no extra imports needed.
export const MONACO_LANGUAGES = [
  { id: "html", label: "HTML" },
  { id: "css", label: "CSS" },
  { id: "scss", label: "SCSS" },
  { id: "less", label: "LESS" },
  { id: "javascript", label: "JavaScript" },
  { id: "typescript", label: "TypeScript (JSX/TSX)" },
  { id: "json", label: "JSON" },
  { id: "xml", label: "XML" },
  { id: "yaml", label: "YAML" },
  { id: "markdown", label: "Markdown" },
  { id: "mdx", label: "MDX" },
  { id: "handlebars", label: "Handlebars" },
  { id: "twig", label: "Twig" },
  { id: "liquid", label: "Liquid" },
  { id: "pug", label: "Pug" },
  { id: "razor", label: "Razor" },
  { id: "graphql", label: "GraphQL" },
  { id: "php", label: "PHP" },
  { id: "python", label: "Python" },
  { id: "ruby", label: "Ruby" },
  { id: "go", label: "Go" },
  { id: "rust", label: "Rust" },
  { id: "java", label: "Java" },
  { id: "kotlin", label: "Kotlin" },
  { id: "swift", label: "Swift" },
  { id: "csharp", label: "C#" },
  { id: "cpp", label: "C++" },
  { id: "c", label: "C" },
  { id: "dart", label: "Dart" },
  { id: "elixir", label: "Elixir" },
  { id: "clojure", label: "Clojure" },
  { id: "scala", label: "Scala" },
  { id: "sql", label: "SQL" },
  { id: "shell", label: "Shell" },
  { id: "powershell", label: "PowerShell" },
  { id: "dockerfile", label: "Dockerfile" },
  { id: "solidity", label: "Solidity" },
  { id: "lua", label: "Lua" },
  { id: "r", label: "R" },
  { id: "perl", label: "Perl" },
  { id: "bicep", label: "Bicep" },
  { id: "hcl", label: "HCL / Terraform" },
];
